# This is a basic workflow to help you get started with Actions

name: getData

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  schedule:
    - cron: '0 */2 * * *' # update every 8 hours

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # - uses: actions/checkout@v2
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: show dir
        run: ls
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
      - run: python crawler.py
